OPENAI_API_KEY="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"


GROQ_API_KEY="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"
